spring:
  config:
    import: optional:file:.env[.properties]   # ←あっても無害、無ければ削ってOK
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  logging:
    level:
      org.flywaydb: DEBUG
      org.springframework: DEBUG

frontend:
  url: ${FRONTEND_URL}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${BACKEND_URL}/api/auth/google/callback
