spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: local

  datasource:
   url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
   username: ${DB_USER}
   password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  logging:
    level:
      org.flywaydb: DEBUG
      org.springframework: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE

frontend:
  url:  ${FRONTEND_URL}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${BACKEND_URL}/api/auth/google/callback

# s3互換のsakuraのクラウドストレージを使う
s3:
  endpoint: ${CLOUD_AWS_S3_ENDPOINT}
  accessKey: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
  secretKey: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
  region: ${CLOUD_AWS_REGION_STATIC}
  bucket: ${BUCKET_NAME}